services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    image: mariadb:1.0
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:1.0
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    image: nginx:1.0
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis:1.0
    container_name: redis
    restart: always
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 6379

  static_site:
    build:
      context: ./requirements/bonus/static_site
    image: static_site:1.0
    container_name: static_site
    restart: always
    networks:
      - inception
    ports:
      - "3000:3000"

  ftp:
    build:
      context: ./requirements/bonus/ftp
    image: ftp:1.0
    container_name: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    depends_on:
      - wordpress

  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: adminer:1.0
    container_name: adminer
    restart: always
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

  portainer:
    build:
      context: ./requirements/bonus/portainer
    image: portainer:1.0
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    ports:
      - "9000:9000"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oait-h-m/data/mariadb
      
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oait-h-m/data/wordpress

  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oait-h-m/data/portainer