services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stop
    env_file:
      - .env
    networks:
      - inception
    port:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oait-h-m/data/mariadb